FROM node:21.7.1 AS builder

WORKDIR /app

COPY ./PSR2024-TP1-FRONT-Montenegro-Ibarrola/Angular/app .

RUN npm install -g @angular/cli

RUN npm install

RUN ng build --configuration=production

CMD ng serve --host 0.0.0.0
